services:
    imageResizerRoute:
        class:     'Opine\ImageResizer\Route'
        arguments: ['@route']
    imageResizer:
        class:     'Opine\ImageResizer\Service'
        arguments: ['@config', '@secret']
    imageResizerController:
        class:     'Opine\ImageResizer\Controller'
        arguments: ['@imageResizer', '@secret']
